### ISSUE TITLE
How do I get file data information?

### ISSUE THREAD

**Issue by TheJPEGJames** [ColinShark/exaroton#3]
I am trying to find some files that are hidden in the backup folder that were saved via textile backup.

What is the command to view/get/delete the files in backups folder?

I'm trying the command below but neither works.
print(exa.get_file_info("Server ID"))

print(exa.get_server("Server ID")_files("Backups"))

**Comment by ColinShark** [comment]
`get_server()` returns a static `Server` object, that doesn't have any bound methods like `.files()`, or and way to traverse any path.

`get_file_info()` isn't a method that exists within my exaroton wrapper. Since I've last checked, the exaroton API itself offers a way to get file data, write file data and delete a file. I'll have to read the APIs documentation on those methods and implement them into my wrapper first. Expect an update in the next few hours or days.

**Comment by ColinShark** [comment]
@TheJPEGJames I have added new methods `get_file_data` and `delete_file_data`. These might not work as expected, as I don't have much time or energy to thoroughly test these. It has given me some trouble as the API doesn't actually return what the documentation says it should. So take the update with a grain of salt.

Once the update hits PyPi, you can update with `pip install -U exaroton`.
