### ISSUE TITLE
Can't get server icon

### ISSUE THREAD

**Issue by rightburrow** [ColinShark/exaroton#4]
I'm trying to get the server icon using get_file_data() and its returning none. How to fix?

**Comment by ColinShark** [comment]
The [API documentation](https://developers.exaroton.com/#file-data) lists `application/octet-stream` as the returned type, but returns `image/png` instead, which makes my if-checks fail 🙃 

[I've updated the code ](https://github.com/ColinShark/exaroton/commit/81fa7e754a55264832e9fe3cfabfd3dbfaf468c4)to check for the undocumented type, it should work now. Since the Wrapper itself doesn't actually handle the file conversion, you may want to use open() yourself and write the file contents manually:

```py
file = exa.get_file_data(...)
with open("server-icon.png", "wb") as f:
    f.write(file)
```
